### ISSUE TITLE
Outdated on Gnome Extensions website

### ISSUE THREAD

**Issue by pauloimon** [maoschanz/sound-percentage-gs-extension#6]
I've installed this extension from [this](https://extensions.gnome.org/extension/2120/sound-percentage/) link, but it seems outdated to me.

Please, I'd like to see the new version oficially available on website too.

This extension helped me a lot!

Thanks!

**Comment by maoschanz** [comment]
i'll not develop support for GNOME 3.40, if it's what you're trying to ask

**Comment by pauloimon** [comment]
I'm using Gnome 3.36 here, but the version I've installed from [here](https://extensions.gnome.org/extension/2120/sound-percentage/) is outdated and not has the microphone percentage on the status bar.

![image](https://user-images.githubusercontent.com/3463932/116490279-57a0f500-a86d-11eb-9001-c5eed50e52b1.png)

**Comment by maoschanz** [comment]
features that have been developed but not released yet are... not released yet, and that's the normal state of things.

3.36 is supported, the extension works = not outdated, sorry. At least not for you, it if was about an issue about Gnome 40 the problem would have been valid (though i would have not fix it because i will not use an environment with horizontal workspaces)
